services:
  - type: web
    name: fastapi-rank-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn player_ranking_predictor:app --bind 0.0.0.0:$PORT
